import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { copyFileSync, mkdirSync, watch } from "node:fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const outdir = "/Volumes/Studio/Fabric/.obsidian/plugins/taskbase";

// Ensure output directory exists
mkdirSync(outdir, { recursive: true });

// Plugin to copy static files after build
const copyPlugin = {
	name: "copy-static",
	setup(build) {
		build.onEnd(() => {
			copyFileSync("manifest.json", `${outdir}/manifest.json`);
			copyFileSync("styles.css", `${outdir}/styles.css`);
			console.log("Copied manifest.json and styles.css to plugin folder");
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: `${outdir}/main.js`,
	minify: prod,
	plugins: [copyPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();

	// Watch static files (styles.css, manifest.json) for changes
	const staticFiles = ["styles.css", "manifest.json"];
	for (const file of staticFiles) {
		watch(file, (eventType) => {
			if (eventType === "change") {
				try {
					copyFileSync(file, `${outdir}/${file}`);
					console.log(`[watch] Copied ${file} to plugin folder`);
				} catch (err) {
					console.error(`[watch] Failed to copy ${file}:`, err.message);
				}
			}
		});
	}
	console.log("Watching for changes (including styles.css and manifest.json)...");
}
